version: "3.4"

services:
    node:
        container_name: pat-rizzardi
        restart: always
        build: .
        env_file: .env
        ports:
            - 5000:5000
        networks:
            - app-network

#Docker Volumes
volumes:
    dbdata:
        driver: local

#Docker Networks
networks:
    app-network:
        driver: bridge