name: Deploy application
 
on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USER }}
          # script: |
          #   KEY=$(date +%Y%m%dT%H%M)
          #   mkdir -p /var/www/fitness-app/releases/$KEY
          #   cd /var/www/fitness-app/releases/$KEY # navigate into the folder
          #   git clone https://github.com/patrickrizz/fitness-app.git . &> /dev/null
          script: |
            /var/www/pat-rizzardi/scripts/deploy.sh
      
#     needs: deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: Discord notification
#         env:
#           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#           DISCORD_USERNAME: "Github"
#         uses: Ilshidur/action-discord@master
#         with:
#           args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
