name: Deploy application
 
on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USER }}
          # script: |
          #   KEY=$(date +%Y%m%dT%H%M)
          #   mkdir -p /var/www/fitness-app/releases/$KEY
          #   cd /var/www/fitness-app/releases/$KEY # navigate into the folder
          #   git clone https://github.com/patrickrizz/fitness-app.git . &> /dev/null
          script: |
            cd /var/www/pat-rizzardi && git pull
      env:
        # Server
        NODE_ENV:         
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        SESSION_SECRET_2: ${{ secrets.SESSION_SECRET_2 }}
        # API Keys
        CLASH_OF_CLANS_TOKEN: ${{ secrets.CLASH_OF_CLANS_TOKEN }}
        GHOST_API: ${{ secrets.GHOST_API }}
        GITHUB_ID: ${{ secrets.GITHUB_ID }}
        GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        # URL
        GHOST_URL: https://blog.patrizzardi.com
        CLASH_OF_CLANS_URL: https://api.clashofclans.com/v1/
        #DB LOGIN
        DB_HOST: mysql
        DB: clash_of_clans
        DB_HOST: localhost
        DB_USER: app
        DB_PASSWORD: 

      
#     needs: deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: Discord notification
#         env:
#           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#           DISCORD_USERNAME: "Github"
#         uses: Ilshidur/action-discord@master
#         with:
#           args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
